# Generated by Django 4.0.4 on 2022-05-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='task',
            new_name='Task',
        ),
    ]
