# Generated by Django 4.0.4 on 2022-05-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_tasklist_manage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='Task',
            new_name='task',
        ),
    ]
