# Generated by Django 4.0.4 on 2022-05-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_rename_task_tasklist_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='manage',
        ),
    ]
